# This file is to be overwritten by nwg-displays if you choose to use it.
# nwg-displays is a graphical tool for managing monitors.
# - Installation for Arch Linux: sudo pacman -S nwg-displays
# - Repo: https://github.com/nwg-piotr/nwg-displays
monitor = DP-3, 2560x1440@144, 0x0, 1
monitor = DP-2, 2560x1440@144, 2560x-560, 1, transform, 3
workspace = 1, monitor:DP-3, default:true
workspace = 2, monitor:DP-2
