# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

exec-once = coolercontroler # Starts the coolercontroller app once at startup

exec-once = hyprsunset # Starts the hyprsunset app once at startup
