# See https://wiki.hyprland.org/Configuring/Binds/
#!
##! Extra keybinds
bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds

# Add stuff here
# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above

$terminal = kitty
$browser = google-chrome-stable
$mainMod = Super

# bind = Super, W, exec, $browser # [hidden]
bind = Super, Grave, exec, $terminal # [hidden]
# bind = Super, E, exec, nautilus --new-window # nautilus (file manager)

bind = Super, Z, exec, zen-browser
