# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

windowrulev2 = center, title:^(steam)$
windowrulev2 = float, title:^(steam)$

windowrulev2 = float, class:^(discord)$
windowrulev2 = float, class:^(discord\.desktop)$
windowrulev2 = center, class:^(discord)$
