local mainMod = "SUPER"
local terminal    = "kitty"
local fileManager = "nautilus"
local menu        = "hyprlauncher"
local browser    = "google-chrome-stable"
local editor      = "visual-studio-code-bin"
local taskManager  = "btop"
local browser2    = "zen-browser"
