mainMod = "SUPER"
terminal    = "kitty"
fileManager = "nautilus"
menu        = "hyprlauncher"
browser    = "google-chrome-stable"
editor      = "visual-studio-code-bin"
taskManager  = "btop"
browser2    = "zen-browser"
